<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210623155114 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ability (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_35CFEE3C82F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE damage_class (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, image VARCHAR(255) NOT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_7BCB5C8782F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE egg_group (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_32F8027682F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evolution_chain (id INT AUTO_INCREMENT NOT NULL, baby_item_trigger_id INT DEFAULT NULL, id_api INT NOT NULL, slug VARCHAR(255) DEFAULT NULL, INDEX IDX_68B11268C260B660 (baby_item_trigger_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evolution_chain_link (id INT AUTO_INCREMENT NOT NULL, from_pokemon_species_id INT DEFAULT NULL, evolution_detail_id INT DEFAULT NULL, evolution_chain_id INT DEFAULT NULL, is_baby SMALLINT NOT NULL, evolution_order INT NOT NULL, INDEX IDX_51633FFAF1095A32 (from_pokemon_species_id), INDEX IDX_51633FFA2C2C0E8 (evolution_detail_id), INDEX IDX_51633FFAE417AC09 (evolution_chain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evolution_detail (id INT AUTO_INCREMENT NOT NULL, gender_id INT DEFAULT NULL, held_item_id INT DEFAULT NULL, used_item_id INT DEFAULT NULL, known_move_id INT DEFAULT NULL, known_move_type_id INT DEFAULT NULL, location_id INT DEFAULT NULL, pokemon_species_id INT DEFAULT NULL, party_type_id INT DEFAULT NULL, trade_species_id INT DEFAULT NULL, evolution_trigger_id INT DEFAULT NULL, min_affection VARCHAR(255) DEFAULT NULL, min_beauty VARCHAR(255) DEFAULT NULL, min_happiness VARCHAR(6) DEFAULT NULL, min_level VARCHAR(255) DEFAULT NULL, needs_overworld_rain SMALLINT DEFAULT NULL, time_of_day VARCHAR(255) DEFAULT NULL, relative_physical_stats VARCHAR(255) DEFAULT NULL, other_detailed VARCHAR(255) DEFAULT NULL, turn_upside_down SMALLINT DEFAULT NULL, INDEX IDX_16070E5D708A0E0 (gender_id), INDEX IDX_16070E5DBD59BEFF (held_item_id), INDEX IDX_16070E5D95B877AF (used_item_id), INDEX IDX_16070E5D189A45FC (known_move_id), INDEX IDX_16070E5D40D850A6 (known_move_type_id), INDEX IDX_16070E5D64D218E (location_id), INDEX IDX_16070E5D609DB477 (pokemon_species_id), INDEX IDX_16070E5DD7BD13B8 (party_type_id), INDEX IDX_16070E5D9C32838D (trade_species_id), INDEX IDX_16070E5DAD65CE5B (evolution_trigger_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evolution_trigger (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_668FE19B82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gender (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_C7470A4282F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE generation (id INT AUTO_INCREMENT NOT NULL, main_region_id INT DEFAULT NULL, language_id INT DEFAULT NULL, number VARCHAR(2) NOT NULL, code VARCHAR(2) NOT NULL, display_order INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_D3266C3BB890A6F7 (main_region_id), INDEX IDX_D3266C3B82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, cost INT DEFAULT NULL, sprite_url VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_1F1B251E82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_description (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_8D8C1810126F525E (item_id), INDEX IDX_8D8C181092AE854F (version_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_held_pokemon (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, pokemon_id INT DEFAULT NULL, INDEX IDX_2B08193126F525E (item_id), INDEX IDX_2B081932FE71C3E (pokemon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_held_pokemon_version (id INT AUTO_INCREMENT NOT NULL, version_id INT DEFAULT NULL, rarity INT DEFAULT NULL, item_held_Pokemon_id INT DEFAULT NULL, INDEX IDX_243020FF4BBC2705 (version_id), INDEX IDX_243020FF3FB0DACD (item_held_Pokemon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(3) NOT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(36) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, region_id INT DEFAULT NULL, language_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_5E9E89CB98260155 (region_id), INDEX IDX_5E9E89CB82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location_area (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, language_id INT DEFAULT NULL, id_api VARCHAR(10) DEFAULT NULL, name_api VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_5790882864D218E (location_id), INDEX IDX_5790882882F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE move (id INT AUTO_INCREMENT NOT NULL, type_id INT DEFAULT NULL, damage_class_id INT DEFAULT NULL, language_id INT DEFAULT NULL, pp INT DEFAULT NULL, accuracy INT DEFAULT NULL, power INT DEFAULT NULL, priority SMALLINT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_EF3E3778C54C8C93 (type_id), INDEX IDX_EF3E37789883C12E (damage_class_id), INDEX IDX_EF3E377882F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE move_description (id INT AUTO_INCREMENT NOT NULL, move_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, language_id INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_83FBA7FC6DC541A8 (move_id), INDEX IDX_83FBA7FC92AE854F (version_group_id), INDEX IDX_83FBA7FC82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE move_learn_method (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, display_order INT DEFAULT NULL, code_method VARCHAR(80) NOT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_EF1CDB882F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE move_machine (id INT AUTO_INCREMENT NOT NULL, move_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, language_id INT DEFAULT NULL, number INT NOT NULL, image_url VARCHAR(255) NOT NULL, cost INT NOT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_E7C819D36DC541A8 (move_id), INDEX IDX_E7C819D392AE854F (version_group_id), INDEX IDX_E7C819D382F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nature (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, stat_increased VARCHAR(120) DEFAULT NULL, stat_decreased VARCHAR(120) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_B1D882A782F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokedex (id INT AUTO_INCREMENT NOT NULL, generation_id INT DEFAULT NULL, language_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_6336F6A7553A6EC4 (generation_id), INDEX IDX_6336F6A782F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokedex_version_group (pokedex_id INT NOT NULL, version_group_id INT NOT NULL, INDEX IDX_66CF0887372A5D14 (pokedex_id), INDEX IDX_66CF088792AE854F (version_group_id), PRIMARY KEY(pokedex_id, version_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokedex_species (id INT AUTO_INCREMENT NOT NULL, pokemon_species_id INT DEFAULT NULL, pokedex_id INT DEFAULT NULL, number INT NOT NULL, INDEX IDX_7AD01E34609DB477 (pokemon_species_id), INDEX IDX_7AD01E34372A5D14 (pokedex_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon (id INT AUTO_INCREMENT NOT NULL, pokemon_sprites_id INT DEFAULT NULL, stats_effort_id INT DEFAULT NULL, pokemon_species_id INT DEFAULT NULL, language_id INT DEFAULT NULL, weight INT DEFAULT NULL, height INT DEFAULT NULL, base_experience INT DEFAULT NULL, is_default SMALLINT DEFAULT NULL, hp INT DEFAULT NULL, atk INT DEFAULT NULL, def INT DEFAULT NULL, spa INT DEFAULT NULL, spd INT DEFAULT NULL, spe INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, id_api VARCHAR(10) DEFAULT NULL, name_api VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_62DC90F3DDBC24E (pokemon_sprites_id), INDEX IDX_62DC90F373CEECA (stats_effort_id), INDEX IDX_62DC90F3609DB477 (pokemon_species_id), INDEX IDX_62DC90F382F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_types (pokemon_id INT NOT NULL, type_id INT NOT NULL, INDEX IDX_B6D930642FE71C3E (pokemon_id), INDEX IDX_B6D93064C54C8C93 (type_id), PRIMARY KEY(pokemon_id, type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_ability (id INT AUTO_INCREMENT NOT NULL, pokemon_id INT DEFAULT NULL, ability_id INT DEFAULT NULL, is_hidden TINYINT(1) DEFAULT NULL, INDEX IDX_59A592AD2FE71C3E (pokemon_id), INDEX IDX_59A592AD8016D8B2 (ability_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_form (id INT AUTO_INCREMENT NOT NULL, pokemon_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, language_id INT DEFAULT NULL, is_mega TINYINT(1) DEFAULT NULL, is_default TINYINT(1) DEFAULT NULL, is_battle_only TINYINT(1) DEFAULT NULL, form_name VARCHAR(255) DEFAULT NULL, form_sprite VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_6E21830C2FE71C3E (pokemon_id), INDEX IDX_6E21830C92AE854F (version_group_id), INDEX IDX_6E21830C82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_moves_learn_version (id INT AUTO_INCREMENT NOT NULL, pokemon_id INT DEFAULT NULL, move_id INT DEFAULT NULL, move_learn_method_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, level INT NOT NULL, slug VARCHAR(255) DEFAULT NULL, INDEX IDX_7364724F2FE71C3E (pokemon_id), INDEX IDX_7364724F6DC541A8 (move_id), INDEX IDX_7364724F19E2011F (move_learn_method_id), INDEX IDX_7364724F92AE854F (version_group_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_sheet (id INT AUTO_INCREMENT NOT NULL, pokemon_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, nature_id INT DEFAULT NULL, ability_id INT DEFAULT NULL, ivs_id INT DEFAULT NULL, evs_id INT DEFAULT NULL, stats_id INT DEFAULT NULL, user_id INT DEFAULT NULL, nickname VARCHAR(20) DEFAULT NULL, level INT NOT NULL, INDEX IDX_68D528B62FE71C3E (pokemon_id), UNIQUE INDEX UNIQ_68D528B6708A0E0 (gender_id), INDEX IDX_68D528B63BCB2E4B (nature_id), INDEX IDX_68D528B68016D8B2 (ability_id), UNIQUE INDEX UNIQ_68D528B6821F90E (ivs_id), UNIQUE INDEX UNIQ_68D528B67FE33975 (evs_id), UNIQUE INDEX UNIQ_68D528B670AA3482 (stats_id), INDEX IDX_68D528B6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_sheet_moves (pokemon_sheet_id INT NOT NULL, move_id INT NOT NULL, INDEX IDX_A56BA330C76CF0B (pokemon_sheet_id), INDEX IDX_A56BA3306DC541A8 (move_id), PRIMARY KEY(pokemon_sheet_id, move_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_species (id INT AUTO_INCREMENT NOT NULL, evolves_from_species_id INT DEFAULT NULL, evolution_chain_id INT DEFAULT NULL, language_id INT DEFAULT NULL, base_happiness INT DEFAULT NULL, capture_rate INT DEFAULT NULL, growth_rate VARCHAR(255) DEFAULT NULL, hatch_counter INT DEFAULT NULL, is_legendary SMALLINT DEFAULT NULL, has_gender_differences SMALLINT DEFAULT NULL, is_mythical SMALLINT DEFAULT NULL, is_baby SMALLINT DEFAULT NULL, genera VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_C9658B837D11D524 (evolves_from_species_id), INDEX IDX_C9658B83E417AC09 (evolution_chain_id), INDEX IDX_C9658B8382F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_species_eggs (pokemon_species_id INT NOT NULL, egg_group_id INT NOT NULL, INDEX IDX_468B36C1609DB477 (pokemon_species_id), INDEX IDX_468B36C1B76DC94C (egg_group_id), PRIMARY KEY(pokemon_species_id, egg_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_species_version (id INT AUTO_INCREMENT NOT NULL, pokemon_species_id INT DEFAULT NULL, version_id INT DEFAULT NULL, language_id INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, INDEX IDX_20CD1ACC609DB477 (pokemon_species_id), INDEX IDX_20CD1ACC4BBC2705 (version_id), INDEX IDX_20CD1ACC82F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_sprites (id INT AUTO_INCREMENT NOT NULL, sprite_icon VARCHAR(255) DEFAULT NULL, sprite_official VARCHAR(255) DEFAULT NULL, sprite_front_default VARCHAR(255) DEFAULT NULL, sprite_front_shiny VARCHAR(255) DEFAULT NULL, sprite_front_female VARCHAR(255) DEFAULT NULL, sprite_female_shiny VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pokemon_sprites_version (id INT AUTO_INCREMENT NOT NULL, pokemon_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, url_default VARCHAR(255) DEFAULT NULL, url_default_shiny VARCHAR(255) DEFAULT NULL, url_default_female VARCHAR(255) DEFAULT NULL, url_default_female_shiny VARCHAR(255) DEFAULT NULL, INDEX IDX_66ECDBE32FE71C3E (pokemon_id), INDEX IDX_66ECDBE392AE854F (version_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_F62F17682F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stats (id INT AUTO_INCREMENT NOT NULL, hp INT DEFAULT NULL, atk INT DEFAULT NULL, def INT DEFAULT NULL, spa INT DEFAULT NULL, spd INT DEFAULT NULL, spe INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stats_effort (id INT AUTO_INCREMENT NOT NULL, hp INT DEFAULT NULL, atk INT DEFAULT NULL, def INT DEFAULT NULL, spa INT DEFAULT NULL, spd INT DEFAULT NULL, spe INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stats_ev (id INT AUTO_INCREMENT NOT NULL, hp INT DEFAULT NULL, atk INT DEFAULT NULL, def INT DEFAULT NULL, spa INT DEFAULT NULL, spd INT DEFAULT NULL, spe INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stats_iv (id INT AUTO_INCREMENT NOT NULL, hp INT DEFAULT NULL, atk INT DEFAULT NULL, def INT DEFAULT NULL, spa INT DEFAULT NULL, spd INT DEFAULT NULL, spe INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, img VARCHAR(255) DEFAULT NULL, code_api VARCHAR(2) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_8CDE572982F1BAF4 (language_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_damage_relation_type (id INT AUTO_INCREMENT NOT NULL, type_id INT DEFAULT NULL, damage_relation_type_id INT DEFAULT NULL, damage_relation VARCHAR(4) NOT NULL, damage_relation_coefficient DOUBLE PRECISION NOT NULL, slug VARCHAR(255) DEFAULT NULL, INDEX IDX_8480E846C54C8C93 (type_id), INDEX IDX_8480E8463F2BCAB1 (damage_relation_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, nickname VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, INDEX IDX_8D93D64982F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE version (id INT AUTO_INCREMENT NOT NULL, version_group_id INT DEFAULT NULL, language_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_BF1CD3C392AE854F (version_group_id), INDEX IDX_BF1CD3C382F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE version_group (id INT AUTO_INCREMENT NOT NULL, generation_id INT DEFAULT NULL, language_id INT DEFAULT NULL, `order` INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_6A1C90C0553A6EC4 (generation_id), INDEX IDX_6A1C90C082F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ability ADD CONSTRAINT FK_35CFEE3C82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE damage_class ADD CONSTRAINT FK_7BCB5C8782F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE egg_group ADD CONSTRAINT FK_32F8027682F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE evolution_chain ADD CONSTRAINT FK_68B11268C260B660 FOREIGN KEY (baby_item_trigger_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE evolution_chain_link ADD CONSTRAINT FK_51633FFAF1095A32 FOREIGN KEY (from_pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE evolution_chain_link ADD CONSTRAINT FK_51633FFA2C2C0E8 FOREIGN KEY (evolution_detail_id) REFERENCES evolution_detail (id)');
        $this->addSql('ALTER TABLE evolution_chain_link ADD CONSTRAINT FK_51633FFAE417AC09 FOREIGN KEY (evolution_chain_id) REFERENCES evolution_chain (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5DBD59BEFF FOREIGN KEY (held_item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D95B877AF FOREIGN KEY (used_item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D189A45FC FOREIGN KEY (known_move_id) REFERENCES move (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D40D850A6 FOREIGN KEY (known_move_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D609DB477 FOREIGN KEY (pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5DD7BD13B8 FOREIGN KEY (party_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5D9C32838D FOREIGN KEY (trade_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE evolution_detail ADD CONSTRAINT FK_16070E5DAD65CE5B FOREIGN KEY (evolution_trigger_id) REFERENCES evolution_trigger (id)');
        $this->addSql('ALTER TABLE evolution_trigger ADD CONSTRAINT FK_668FE19B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE gender ADD CONSTRAINT FK_C7470A4282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE generation ADD CONSTRAINT FK_D3266C3BB890A6F7 FOREIGN KEY (main_region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE generation ADD CONSTRAINT FK_D3266C3B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE item_description ADD CONSTRAINT FK_8D8C1810126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE item_description ADD CONSTRAINT FK_8D8C181092AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE item_held_pokemon ADD CONSTRAINT FK_2B08193126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE item_held_pokemon ADD CONSTRAINT FK_2B081932FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE item_held_pokemon_version ADD CONSTRAINT FK_243020FF4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id)');
        $this->addSql('ALTER TABLE item_held_pokemon_version ADD CONSTRAINT FK_243020FF3FB0DACD FOREIGN KEY (item_held_Pokemon_id) REFERENCES item_held_pokemon (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB98260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE location_area ADD CONSTRAINT FK_5790882864D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE location_area ADD CONSTRAINT FK_5790882882F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E37789883C12E FOREIGN KEY (damage_class_id) REFERENCES damage_class (id)');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E377882F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE move_description ADD CONSTRAINT FK_83FBA7FC6DC541A8 FOREIGN KEY (move_id) REFERENCES move (id)');
        $this->addSql('ALTER TABLE move_description ADD CONSTRAINT FK_83FBA7FC92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE move_description ADD CONSTRAINT FK_83FBA7FC82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE move_learn_method ADD CONSTRAINT FK_EF1CDB882F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE move_machine ADD CONSTRAINT FK_E7C819D36DC541A8 FOREIGN KEY (move_id) REFERENCES move (id)');
        $this->addSql('ALTER TABLE move_machine ADD CONSTRAINT FK_E7C819D392AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE move_machine ADD CONSTRAINT FK_E7C819D382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A782F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokedex ADD CONSTRAINT FK_6336F6A7553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id)');
        $this->addSql('ALTER TABLE pokedex ADD CONSTRAINT FK_6336F6A782F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokedex_version_group ADD CONSTRAINT FK_66CF0887372A5D14 FOREIGN KEY (pokedex_id) REFERENCES pokedex (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pokedex_version_group ADD CONSTRAINT FK_66CF088792AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pokedex_species ADD CONSTRAINT FK_7AD01E34609DB477 FOREIGN KEY (pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE pokedex_species ADD CONSTRAINT FK_7AD01E34372A5D14 FOREIGN KEY (pokedex_id) REFERENCES pokedex (id)');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3DDBC24E FOREIGN KEY (pokemon_sprites_id) REFERENCES pokemon_sprites (id)');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F373CEECA FOREIGN KEY (stats_effort_id) REFERENCES stats_effort (id)');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3609DB477 FOREIGN KEY (pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokemon_types ADD CONSTRAINT FK_B6D930642FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_types ADD CONSTRAINT FK_B6D93064C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE pokemon_ability ADD CONSTRAINT FK_59A592AD2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_ability ADD CONSTRAINT FK_59A592AD8016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id)');
        $this->addSql('ALTER TABLE pokemon_form ADD CONSTRAINT FK_6E21830C2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_form ADD CONSTRAINT FK_6E21830C92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE pokemon_form ADD CONSTRAINT FK_6E21830C82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version ADD CONSTRAINT FK_7364724F2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version ADD CONSTRAINT FK_7364724F6DC541A8 FOREIGN KEY (move_id) REFERENCES move (id)');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version ADD CONSTRAINT FK_7364724F19E2011F FOREIGN KEY (move_learn_method_id) REFERENCES move_learn_method (id)');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version ADD CONSTRAINT FK_7364724F92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B62FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B6708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B63BCB2E4B FOREIGN KEY (nature_id) REFERENCES nature (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B68016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B6821F90E FOREIGN KEY (ivs_id) REFERENCES stats_iv (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B67FE33975 FOREIGN KEY (evs_id) REFERENCES stats_ev (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B670AA3482 FOREIGN KEY (stats_id) REFERENCES stats (id)');
        $this->addSql('ALTER TABLE pokemon_sheet ADD CONSTRAINT FK_68D528B6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE pokemon_sheet_moves ADD CONSTRAINT FK_A56BA330C76CF0B FOREIGN KEY (pokemon_sheet_id) REFERENCES pokemon_sheet (id)');
        $this->addSql('ALTER TABLE pokemon_sheet_moves ADD CONSTRAINT FK_A56BA3306DC541A8 FOREIGN KEY (move_id) REFERENCES move (id)');
        $this->addSql('ALTER TABLE pokemon_species ADD CONSTRAINT FK_C9658B837D11D524 FOREIGN KEY (evolves_from_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE pokemon_species ADD CONSTRAINT FK_C9658B83E417AC09 FOREIGN KEY (evolution_chain_id) REFERENCES evolution_chain (id)');
        $this->addSql('ALTER TABLE pokemon_species ADD CONSTRAINT FK_C9658B8382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokemon_species_eggs ADD CONSTRAINT FK_468B36C1609DB477 FOREIGN KEY (pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE pokemon_species_eggs ADD CONSTRAINT FK_468B36C1B76DC94C FOREIGN KEY (egg_group_id) REFERENCES egg_group (id)');
        $this->addSql('ALTER TABLE pokemon_species_version ADD CONSTRAINT FK_20CD1ACC609DB477 FOREIGN KEY (pokemon_species_id) REFERENCES pokemon_species (id)');
        $this->addSql('ALTER TABLE pokemon_species_version ADD CONSTRAINT FK_20CD1ACC4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id)');
        $this->addSql('ALTER TABLE pokemon_species_version ADD CONSTRAINT FK_20CD1ACC82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE pokemon_sprites_version ADD CONSTRAINT FK_66ECDBE32FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id)');
        $this->addSql('ALTER TABLE pokemon_sprites_version ADD CONSTRAINT FK_66ECDBE392AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F17682F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE type_damage_relation_type ADD CONSTRAINT FK_8480E846C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE type_damage_relation_type ADD CONSTRAINT FK_8480E8463F2BCAB1 FOREIGN KEY (damage_relation_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C392AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE version_group ADD CONSTRAINT FK_6A1C90C0553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id)');
        $this->addSql('ALTER TABLE version_group ADD CONSTRAINT FK_6A1C90C082F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE ability_version_group ADD version_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ability_version_group ADD CONSTRAINT FK_6B1D56B18016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id)');
        $this->addSql('ALTER TABLE ability_version_group ADD CONSTRAINT FK_6B1D56B192AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id)');
        $this->addSql('ALTER TABLE ability_version_group ADD CONSTRAINT FK_6B1D56B182F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('CREATE INDEX IDX_6B1D56B192AE854F ON ability_version_group (version_group_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ability_version_group DROP FOREIGN KEY FK_6B1D56B18016D8B2');
        $this->addSql('ALTER TABLE pokemon_ability DROP FOREIGN KEY FK_59A592AD8016D8B2');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B68016D8B2');
        $this->addSql('ALTER TABLE move DROP FOREIGN KEY FK_EF3E37789883C12E');
        $this->addSql('ALTER TABLE pokemon_species_eggs DROP FOREIGN KEY FK_468B36C1B76DC94C');
        $this->addSql('ALTER TABLE evolution_chain_link DROP FOREIGN KEY FK_51633FFAE417AC09');
        $this->addSql('ALTER TABLE pokemon_species DROP FOREIGN KEY FK_C9658B83E417AC09');
        $this->addSql('ALTER TABLE evolution_chain_link DROP FOREIGN KEY FK_51633FFA2C2C0E8');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5DAD65CE5B');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D708A0E0');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B6708A0E0');
        $this->addSql('ALTER TABLE pokedex DROP FOREIGN KEY FK_6336F6A7553A6EC4');
        $this->addSql('ALTER TABLE version_group DROP FOREIGN KEY FK_6A1C90C0553A6EC4');
        $this->addSql('ALTER TABLE evolution_chain DROP FOREIGN KEY FK_68B11268C260B660');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5DBD59BEFF');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D95B877AF');
        $this->addSql('ALTER TABLE item_description DROP FOREIGN KEY FK_8D8C1810126F525E');
        $this->addSql('ALTER TABLE item_held_pokemon DROP FOREIGN KEY FK_2B08193126F525E');
        $this->addSql('ALTER TABLE item_held_pokemon_version DROP FOREIGN KEY FK_243020FF3FB0DACD');
        $this->addSql('ALTER TABLE ability DROP FOREIGN KEY FK_35CFEE3C82F1BAF4');
        $this->addSql('ALTER TABLE ability_version_group DROP FOREIGN KEY FK_6B1D56B182F1BAF4');
        $this->addSql('ALTER TABLE damage_class DROP FOREIGN KEY FK_7BCB5C8782F1BAF4');
        $this->addSql('ALTER TABLE egg_group DROP FOREIGN KEY FK_32F8027682F1BAF4');
        $this->addSql('ALTER TABLE evolution_trigger DROP FOREIGN KEY FK_668FE19B82F1BAF4');
        $this->addSql('ALTER TABLE gender DROP FOREIGN KEY FK_C7470A4282F1BAF4');
        $this->addSql('ALTER TABLE generation DROP FOREIGN KEY FK_D3266C3B82F1BAF4');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E82F1BAF4');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB82F1BAF4');
        $this->addSql('ALTER TABLE location_area DROP FOREIGN KEY FK_5790882882F1BAF4');
        $this->addSql('ALTER TABLE move DROP FOREIGN KEY FK_EF3E377882F1BAF4');
        $this->addSql('ALTER TABLE move_description DROP FOREIGN KEY FK_83FBA7FC82F1BAF4');
        $this->addSql('ALTER TABLE move_learn_method DROP FOREIGN KEY FK_EF1CDB882F1BAF4');
        $this->addSql('ALTER TABLE move_machine DROP FOREIGN KEY FK_E7C819D382F1BAF4');
        $this->addSql('ALTER TABLE nature DROP FOREIGN KEY FK_B1D882A782F1BAF4');
        $this->addSql('ALTER TABLE pokedex DROP FOREIGN KEY FK_6336F6A782F1BAF4');
        $this->addSql('ALTER TABLE pokemon DROP FOREIGN KEY FK_62DC90F382F1BAF4');
        $this->addSql('ALTER TABLE pokemon_form DROP FOREIGN KEY FK_6E21830C82F1BAF4');
        $this->addSql('ALTER TABLE pokemon_species DROP FOREIGN KEY FK_C9658B8382F1BAF4');
        $this->addSql('ALTER TABLE pokemon_species_version DROP FOREIGN KEY FK_20CD1ACC82F1BAF4');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F17682F1BAF4');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572982F1BAF4');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64982F1BAF4');
        $this->addSql('ALTER TABLE version DROP FOREIGN KEY FK_BF1CD3C382F1BAF4');
        $this->addSql('ALTER TABLE version_group DROP FOREIGN KEY FK_6A1C90C082F1BAF4');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D64D218E');
        $this->addSql('ALTER TABLE location_area DROP FOREIGN KEY FK_5790882864D218E');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D189A45FC');
        $this->addSql('ALTER TABLE move_description DROP FOREIGN KEY FK_83FBA7FC6DC541A8');
        $this->addSql('ALTER TABLE move_machine DROP FOREIGN KEY FK_E7C819D36DC541A8');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version DROP FOREIGN KEY FK_7364724F6DC541A8');
        $this->addSql('ALTER TABLE pokemon_sheet_moves DROP FOREIGN KEY FK_A56BA3306DC541A8');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version DROP FOREIGN KEY FK_7364724F19E2011F');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B63BCB2E4B');
        $this->addSql('ALTER TABLE pokedex_version_group DROP FOREIGN KEY FK_66CF0887372A5D14');
        $this->addSql('ALTER TABLE pokedex_species DROP FOREIGN KEY FK_7AD01E34372A5D14');
        $this->addSql('ALTER TABLE item_held_pokemon DROP FOREIGN KEY FK_2B081932FE71C3E');
        $this->addSql('ALTER TABLE pokemon_types DROP FOREIGN KEY FK_B6D930642FE71C3E');
        $this->addSql('ALTER TABLE pokemon_ability DROP FOREIGN KEY FK_59A592AD2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_form DROP FOREIGN KEY FK_6E21830C2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version DROP FOREIGN KEY FK_7364724F2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B62FE71C3E');
        $this->addSql('ALTER TABLE pokemon_sprites_version DROP FOREIGN KEY FK_66ECDBE32FE71C3E');
        $this->addSql('ALTER TABLE pokemon_sheet_moves DROP FOREIGN KEY FK_A56BA330C76CF0B');
        $this->addSql('ALTER TABLE evolution_chain_link DROP FOREIGN KEY FK_51633FFAF1095A32');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D609DB477');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D9C32838D');
        $this->addSql('ALTER TABLE pokedex_species DROP FOREIGN KEY FK_7AD01E34609DB477');
        $this->addSql('ALTER TABLE pokemon DROP FOREIGN KEY FK_62DC90F3609DB477');
        $this->addSql('ALTER TABLE pokemon_species DROP FOREIGN KEY FK_C9658B837D11D524');
        $this->addSql('ALTER TABLE pokemon_species_eggs DROP FOREIGN KEY FK_468B36C1609DB477');
        $this->addSql('ALTER TABLE pokemon_species_version DROP FOREIGN KEY FK_20CD1ACC609DB477');
        $this->addSql('ALTER TABLE pokemon DROP FOREIGN KEY FK_62DC90F3DDBC24E');
        $this->addSql('ALTER TABLE generation DROP FOREIGN KEY FK_D3266C3BB890A6F7');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB98260155');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B670AA3482');
        $this->addSql('ALTER TABLE pokemon DROP FOREIGN KEY FK_62DC90F373CEECA');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B67FE33975');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B6821F90E');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5D40D850A6');
        $this->addSql('ALTER TABLE evolution_detail DROP FOREIGN KEY FK_16070E5DD7BD13B8');
        $this->addSql('ALTER TABLE move DROP FOREIGN KEY FK_EF3E3778C54C8C93');
        $this->addSql('ALTER TABLE pokemon_types DROP FOREIGN KEY FK_B6D93064C54C8C93');
        $this->addSql('ALTER TABLE type_damage_relation_type DROP FOREIGN KEY FK_8480E846C54C8C93');
        $this->addSql('ALTER TABLE type_damage_relation_type DROP FOREIGN KEY FK_8480E8463F2BCAB1');
        $this->addSql('ALTER TABLE pokemon_sheet DROP FOREIGN KEY FK_68D528B6A76ED395');
        $this->addSql('ALTER TABLE item_held_pokemon_version DROP FOREIGN KEY FK_243020FF4BBC2705');
        $this->addSql('ALTER TABLE pokemon_species_version DROP FOREIGN KEY FK_20CD1ACC4BBC2705');
        $this->addSql('ALTER TABLE ability_version_group DROP FOREIGN KEY FK_6B1D56B192AE854F');
        $this->addSql('ALTER TABLE item_description DROP FOREIGN KEY FK_8D8C181092AE854F');
        $this->addSql('ALTER TABLE move_description DROP FOREIGN KEY FK_83FBA7FC92AE854F');
        $this->addSql('ALTER TABLE move_machine DROP FOREIGN KEY FK_E7C819D392AE854F');
        $this->addSql('ALTER TABLE pokedex_version_group DROP FOREIGN KEY FK_66CF088792AE854F');
        $this->addSql('ALTER TABLE pokemon_form DROP FOREIGN KEY FK_6E21830C92AE854F');
        $this->addSql('ALTER TABLE pokemon_moves_learn_version DROP FOREIGN KEY FK_7364724F92AE854F');
        $this->addSql('ALTER TABLE pokemon_sprites_version DROP FOREIGN KEY FK_66ECDBE392AE854F');
        $this->addSql('ALTER TABLE version DROP FOREIGN KEY FK_BF1CD3C392AE854F');
        $this->addSql('DROP TABLE ability');
        $this->addSql('DROP TABLE damage_class');
        $this->addSql('DROP TABLE egg_group');
        $this->addSql('DROP TABLE evolution_chain');
        $this->addSql('DROP TABLE evolution_chain_link');
        $this->addSql('DROP TABLE evolution_detail');
        $this->addSql('DROP TABLE evolution_trigger');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE generation');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_description');
        $this->addSql('DROP TABLE item_held_pokemon');
        $this->addSql('DROP TABLE item_held_pokemon_version');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE location_area');
        $this->addSql('DROP TABLE move');
        $this->addSql('DROP TABLE move_description');
        $this->addSql('DROP TABLE move_learn_method');
        $this->addSql('DROP TABLE move_machine');
        $this->addSql('DROP TABLE nature');
        $this->addSql('DROP TABLE pokedex');
        $this->addSql('DROP TABLE pokedex_version_group');
        $this->addSql('DROP TABLE pokedex_species');
        $this->addSql('DROP TABLE pokemon');
        $this->addSql('DROP TABLE pokemon_types');
        $this->addSql('DROP TABLE pokemon_ability');
        $this->addSql('DROP TABLE pokemon_form');
        $this->addSql('DROP TABLE pokemon_moves_learn_version');
        $this->addSql('DROP TABLE pokemon_sheet');
        $this->addSql('DROP TABLE pokemon_sheet_moves');
        $this->addSql('DROP TABLE pokemon_species');
        $this->addSql('DROP TABLE pokemon_species_eggs');
        $this->addSql('DROP TABLE pokemon_species_version');
        $this->addSql('DROP TABLE pokemon_sprites');
        $this->addSql('DROP TABLE pokemon_sprites_version');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE stats');
        $this->addSql('DROP TABLE stats_effort');
        $this->addSql('DROP TABLE stats_ev');
        $this->addSql('DROP TABLE stats_iv');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE type_damage_relation_type');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE version');
        $this->addSql('DROP TABLE version_group');
        $this->addSql('DROP INDEX IDX_6B1D56B192AE854F ON ability_version_group');
        $this->addSql('ALTER TABLE ability_version_group DROP version_group_id');
    }
}
