<?php

namespace App\DataFixtures;

use App\Entity\Infos\Abilities;
use App\Entity\Infos\Gender;
use App\Entity\Infos\Nature;
use App\Entity\Infos\Type;
use App\Entity\Pokemon\Pokemon;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\ORM\Tools\Console\Command\GenerateRepositoriesCommand;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        /* Gender */
        $genderMale = new Gender();
        $genderMale->setName("Mâle");
        $manager->persist($genderMale);
        $genderFemale = new Gender();
        $genderFemale->setName("Femelle");
        $manager->persist($genderFemale);
        $genderAsexue = new Gender();
        $genderAsexue->setName("Asexué");
        $manager->persist($genderAsexue);
        /* Nature */
        $assure = new Nature();
        $assure->setName("Assuré");
        $assure->setNameEn("Bold");
        $assure->setStatsBonus("+def");
        $assure->setStatsPenalty("-atk");
        $manager->persist($assure);
        $bizarre = new Nature();
        $bizarre->setName("Bizarre");
        $bizarre->setNameEn("Quirky");
        $manager->persist($bizarre);
        $brave = new Nature();
        $brave->setName("Brave");
        $brave->setNameEn("Brave");
        $assure->setStatsBonus("+atk");
        $assure->setStatsPenalty("-spe");
        $manager->persist($brave);
        $calme = new Nature();
        $calme->setName("Calme");
        $calme->setNameEn("Calm");
        $calme->setStatsBonus("+spd");
        $calme->setStatsPenalty("-atk");
        $manager->persist($calme);
        $discret = new Nature();
        $discret->setName("Discret");
        $discret->setNameEn("Quiet");
        $discret->setStatsBonus("+spa");
        $discret->setStatsPenalty("-spe");
        $manager->persist($discret);
        $docile = new Nature();
        $docile->setName("Docile");
        $docile->setNameEn("Docile");
        $manager->persist($docile);
        $doux = new Nature();
        $doux->setName("Doux");
        $doux->setNameEn("Mild");
        $doux->setStatsBonus("+spa");
        $doux->setStatsPenalty("-def");
        $manager->persist($doux);
        $foufou = new Nature();
        $foufou->setName("Foufou");
        $foufou->setNameEn("Rash");
        $foufou->setStatsBonus("+spa");
        $foufou->setStatsPenalty("-spd");
        $manager->persist($foufou);
        $gentil = new Nature();
        $gentil->setName("Gentil");
        $gentil->setNameEn("Gentle");
        $gentil->setStatsBonus("+spd");
        $gentil->setStatsPenalty("-def");
        $manager->persist($gentil);
        $hardi = new Nature();
        $hardi->setName("Hardi");
        $hardi->setNameEn("Hardy");
        $manager->persist($hardi);
        $jovial = new Nature();
        $jovial->setName("Jovial");
        $jovial->setNameEn("Jolly");
        $jovial->setStatsBonus("+spe");
        $jovial->setStatsPenalty("-spa");
        $manager->persist($jovial);
        $lache = new Nature();
        $lache->setName("Lâche");
        $lache->setNameEn("Lax");
        $lache->setStatsBonus("+def");
        $lache->setStatsPenalty("-spd");
        $manager->persist($lache);
        $malin = new Nature();
        $malin->setName("Malin");
        $malin->setNameEn("Impish");
        $malin->setStatsBonus("+def");
        $malin->setStatsPenalty("-spa");
        $manager->persist($malin);
        $malpoli = new Nature();
        $malpoli->setName("Malpoli");
        $malpoli->setNameEn("Sassy");
        $malpoli->setStatsBonus("+spd");
        $malpoli->setStatsPenalty("-spe");
        $manager->persist($malpoli);
        $mauvais = new Nature();
        $mauvais->setName("Mauvais");
        $mauvais->setNameEn("Naughty");
        $mauvais->setStatsBonus("+atk");
        $mauvais->setStatsPenalty("-spd");
        $manager->persist($mauvais);
        $modeste = new Nature();
        $modeste->setName("Modeste");
        $modeste->setNameEn("Modest");
        $modeste->setStatsBonus("+spa");
        $modeste->setStatsPenalty("-atk");
        $manager->persist($modeste);
        $naif = new Nature();
        $naif->setName("Naif");
        $naif->setNameEn("Naive");
        $naif->setStatsBonus("+spe");
        $naif->setStatsPenalty("-spd");
        $manager->persist($naif);
        $presse = new Nature();
        $presse->setName("Pressé");
        $presse->setNameEn("Hasty");
        $presse->setStatsBonus("+spe");
        $presse->setStatsPenalty("-def");
        $manager->persist($presse);
        $prudent = new Nature();
        $prudent->setName("Prudent");
        $prudent->setNameEn("Careful");
        $prudent->setStatsBonus("+spd");
        $prudent->setStatsPenalty("-spa");
        $manager->persist($prudent);
        $pudique = new Nature();
        $pudique->setName("Pudique");
        $pudique->setNameEn("Bashful");
        $manager->persist($pudique);
        $relax = new Nature();
        $relax->setName("Relax");
        $relax->setNameEn("Relaxed");
        $relax->setStatsBonus("+def");
        $relax->setStatsPenalty("-spe");
        $manager->persist($relax);
        $rigide = new Nature();
        $rigide->setName("Rigide");
        $rigide->setNameEn("Adamant");
        $rigide->setStatsBonus("+atk");
        $rigide->setStatsPenalty("-spa");
        $manager->persist($rigide);
        $serieux = new Nature();
        $serieux->setName("Serieux");
        $serieux->setNameEn("Serious");
        $manager->persist($serieux);
        $solo = new Nature();
        $solo->setName("Solo");
        $solo->setNameEn("Lonely");
        $solo->setStatsBonus("+atk");
        $solo->setStatsPenalty("-def");
        $manager->persist($solo);
        $timide = new Nature();
        $timide->setName("Timide");
        $timide->setNameEn("Timid");
        $timide->setStatsBonus("+spe");
        $timide->setStatsPenalty("-atk");
        $manager->persist($timide);
        $manager->flush();
    }
}
